export const grupos = [
  "biologia celular",
  "biotecnologia y sociedad",
  "calculo diferencial e integral",
  "comunic. y sist. de informacion (taller)",
  "fisica de la energia",
  "fisica del movimiento",
  "ingles i",
  "planeacion",
  "programacion (taller)",
  "quimica general",
  "algebra vectorial",
  "estadistica",
  "ingles ii",
  "lab. tec. microbiologicas",
  "quimica organica",
  "relaciones laborales",
  "termodinamica i",
  "aplicaciones matematicas (taller)",
  "balance de materia y energia",
  "ecuaciones diferenciales",
  "etica (taller)",
  "fisiologia celular",
  "ingles iii",
  "lab. de bioingenieria",
  "lab. de biorreactores",
  "metodos cuantitativos",
  "termodinamica ii",
  "electromecanica de procesos",
  "fenomenos de transporte",
  "dinamica y control de bioprocesos",
  "ingenieria enzimatica",
  "lab. biotecnologia molecular",
  "lab. de bioseparaciones",
  "metodos numericos (taller)",
  "administracion de la produccion",
  "biotecnologia de la resp.inmune",
  "lab. de bioconversiones",
  "mecanica de fluidos y solidos",
  "procs. de transf.de calor",
  "proteccion ambiental",
  "sistemas de calidad",
  "tec.de recombinacion genetica",
  "administracion de proyectos",
  "bioseparaciones fluido-fluido",
  "bioseparaciones mecanicas",
  "bioseparaciones solido-fluido",
  "ingenieria de biorreactores",
  "ingenieria celular",
  "topicos selectos de biotecnologia i",
  "topicos selectos de biotecnologia ii",
  "topicos selectos de diseño i",
  "topicos selectos de diseño ii",
  "diseño de procesos de separacion (taller)",
  "electiva i",
  "electiva ii",
  "electiva iii",
  "sintesis y analisis de bioprocesos",
  "tec.de la prod.de biomoleculas",
  "diseño de plantas (taller)",
  "estancia de titulacion",
  "formulacion y evaluacion de proyectos",
];
