// laboratorio/src/constants/locations.ts
export const LOCATIONS = [
    "Estante abierto 1, Nivel 1",
    "Estante abierto 1, Nivel 2",
    "Estante abierto 1, Nivel 3",
    "Estante abierto 2, Nivel 1",
    "Estante abierto 2, Nivel 2",
    "Estante abierto 2, Nivel 3",
    "Estante abierto 2, Nivel 4",
    "Estante abierto 2, Nivel 5",
    "Estante abierto 2, Nivel 6",
    "Estante cerrado 1, Nivel 1",
    "Estante cerrado 1, Nivel 2",
    "Estante cerrado 1, Nivel 3",
    "Estante cerrado 1, Nivel 4",
    "Estante cerrado 1, Nivel 5",
    "Estante cerrado 1, Nivel 6",
    "Estante cerrado 2, Nivel 1",
    "Estante cerrado 2, Nivel 2",
    "Estante cerrado 2, Nivel 3",
    "Estante cerrado 2, Nivel 4",
    "Estante cerrado 2, Nivel 5",
    "Estante cerrado 2, Nivel 6",
    "Estante cerrado 3, Nivel 1",
    "Estante cerrado 3, Nivel 2",
    "Estante cerrado 3, Nivel 3",
    "Estante cerrado 3, Nivel 4",
    "G10",
    "Mesa",
    "Mesa Movible",
  ];
  