import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ClientProviders from "@/providers/providers";

export const metadata: Metadata = {
  title: "Laboratorio",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={"bg-background font-sans antialiased h-screen"}>
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
