import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ClientProviders from "@/providers/providers";

export const metadata: Metadata = {
  title: "Laboratoio",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={"min-h-screen bg-background font-sans antialiased"}>
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
